<div class="card mb-6">
                                            <div class="card-body d-flex align-items-center">
                                                <div>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                        fill="var(--fc-primary)" class="bi bi-phone"
                                                        viewBox="0 0 16 16">
                                                        <path
                                                            d="M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h6zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H5z" />
                                                        <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                                                    </svg>
                                                </div>
                                                <div class="ms-3">
                                                    <p class="mb-0 small">
                                                        Contactanos al <strong>+54 370 412-3456</strong> para asistencia
                                                        con tus pedidos.
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="card-body d-flex align-items-center border-top">
                                                <div>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                        fill="var(--fc-primary)" class="bi bi-truck"
                                                        viewBox="0 0 16 16">
                                                        <path d="M11 1a1 1 0 0 1 1 1v9H4V2a1 1 0 0 1 1-1h6z" />
                                                        <path
                                                            d="M1 6v5h2a3 3 0 1 1 6 0h2a3 3 0 1 1 6 0h2V7a1 1 0 0 0-1-1h-1.5a1 1 0 0 0-1 1V8h-1V6h-3v6H1V6z" />
                                                    </svg>
                                                </div>
                                                <div class="ms-3">
                                                    <p class="mb-0 small">
                                                        Realizá tu pedido hoy y recibí tu mercadería según el cronograma
                                                        de entregas de tu zona.
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="card-body d-flex align-items-center border-top">
                                                <div>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                        fill="var(--fc-primary)" class="bi bi-cart-check"
                                                        viewBox="0 0 16 16">
                                                        <path fill-rule="evenodd"
                                                            d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4H5v-.5A2.5 2.5 0 0 1 8 1z" />
                                                        <path
                                                            d="M0 3.5A.5.5 0 0 1 .5 3H2a.5.5 0 0 1 .485.379L2.89 6H14.5a.5.5 0 0 1 .49.606l-1.5 7A.5.5 0 0 1 13 14H4a.5.5 0 0 1-.49-.394L1.61 6.607 1.11 4H.5a.5.5 0 0 1-.5-.5zM4.102 7L5 12h8.901l1.2-5H4.102z" />
                                                        <path fill-rule="evenodd"
                                                            d="M7.354 11.146a.5.5 0 0 1 .708 0L9 12.293l2.146-2.147a.5.5 0 0 1 .708.708l-2.5 2.5a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 0-.708z" />
                                                    </svg>
                                                </div>
                                                <div class="ms-3">
                                                    <p class="mb-0 small">
                                                        Comprá con confianza. Somos una Distribuidora con más de 10 años
                                                        en el mercado.
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="card-body d-flex align-items-center border-top">
                                                <div>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                        fill="var(--fc-primary)" class="bi bi-clock"
                                                        viewBox="0 0 16 16">
                                                        <path
                                                            d="M8 3.5a.5.5 0 0 1 .5.5v4l3 2a.5.5 0 0 1-.5.866l-3.5-2A.5.5 0 0 1 7 8V4a.5.5 0 0 1 .5-.5z" />
                                                        <path
                                                            d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM1.5 8a6.5 6.5 0 1 1 13 0A6.5 6.5 0 0 1 1.5 8z" />
                                                    </svg>
                                                </div>
                                                <div class="ms-3">
                                                    <p class="mb-0 small">
                                                        Nuestra plataforma de pedidos está disponible las 24 horas del
                                                        día, todos los días.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>